---
plugins:
  - import
  - jest
  - flowtype

env:
  node: true
  jest: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:flowtype/recommended'

rules:
  no-console: warn
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
